#!/usr/bin/env bash
# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to redirect /redirect_me to another page with a 301 status code
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    location /redirect_me {
        return 301 https://www.youtube.com;
    }
    location / {
        return 200 "Hello World!";
    }
}
EOF'

# Restart Nginx
sudo service nginx restart
