#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure redirect from /redirect_me to another page
echo "location /redirect_me {
        return 301 https://www.youtube.com/;
}" | sudo tee /etc/nginx/sites-available/redirect_me

# Configure custom 404 page
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        error_page 404 /404.html;
        location = /404.html {
                internal;
                root /etc/nginx/html;
                echo 'Ceci n\'est pas une page';
        }
}" | sudo tee /etc/nginx/sites-available/custom_404

# Enable the sites
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Restart Nginx
sudo service nginx restart
