#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  yianjr-frontend
        bind *:80
        mode http
        default_backend yianjr-backend
backend yianjr-backend
        balance roundrobin
        server 76965-web-01 34.224.94.59:80 check
        server 76965-web-02 54.160.91.8:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
