#!/usr/bin/env bash

# Update and install necessary tools
sudo apt update
sudo apt upgrade
sudo apt install net-tools nginx

# Check Nginx status
sudo service nginx status

# Verify Nginx is listening on port 80
sudo netstat -tuln | grep 80

# Edit Nginx configuration file
sudo sed -i 's/#include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;/g' /etc/nginx/nginx.conf

# Edit default Nginx site configuration
sudo sed -i 's/#listen 80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/#listen \[::\]:80 default_server;/listen \[::\]:80 default_server;/g' /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart

# Verify Nginx is now listening on port 80
sudo netstat -tuln | grep 80
