#!/usr/bin/env bash
#Script that gives you information about the school file.

if [ -e "school" ]
then
	echo "school file exits"
	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "school" ]
	then
		echo "school file is regular file"
	fi
else
	echo "school file does not exit"
fi
